name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:      
    - uses: actions/checkout@v2
    - name: Flutter action
      # You may pin to the exact commit or the version.
      # uses: subosito/flutter-action@40bc2f6940785fd81048dc949a68866be510469e
      uses: subosito/flutter-action@v1.3.2
      #with:
        # The Flutter version to make available on the path
        #flutter-version: # optional
        # The Flutter build release channel
        #channel: # optional, default is stable

    - name: Install dependencies
      working-directory: FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter
      run: flutter pub get
    - name: Run tests
      working-directory: FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter
      run: flutter pub run test
